apiVersion: v1
kind: Pod
metadata:
  name: pod-02
spec:
  containers:
    - name: nginx
      image: nginx
    - name: nginx-content
      image: pavanidevops78/kubernetes:v3
      volumeMounts:
        - name: my-volume
          mountPath: /usr/share/nginx/html/sample.html




