apiVersion: v1
kind: Pod
metadata:
  name: pod-03
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
    - name: nginx-content
      image: pavanidevops78/kubernetes:image
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html/index.html
  volumes:
    - name: nginx-path
      emptyDir: {}