apiVersion: v1
kind: Pod
metadata:
  name: volume1
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: pavanidevops78/kubernetes:v1
        name: nginx-path
  volumes:
  - name: nginx-path
    emptyDir: {}