apiVersion: v1
kind: Pod
metadata:
  name: pod-05
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Always
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
    - name: nginx-content
      image: pavanidevops78/kubernetes:v3
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-path
      emptyDir: {}