apiVersion: v1
kind: Pod
metadata:
  name: example-init
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
  initContainers:
    - name: image-content
      image: pavanidevops78/kubernetes:i1
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-path
      emptyDir: {}