apiVersion: v1
kind: Pod
metadata:
  name: pod-07
spec:
  containers:
  - name: receive
    image: public.ecr.aws/u4j6q5s8/receive-db:v1
    volumeMounts:
    - name: data-path
      mountPath: /data
  initContainers:
  - name: send
    image:  public.ecr.aws/u4j6q5s8/send-db:v1
    env:
    - name: "DB_HOST"
      value: "MYSQL"
      volumeMounts:
      - name: data-path
        mountPath: /data
  volumes:
  - name: data-path
    emptyDir: {}

