apiVersion: v1
kind: Pod
metadata:
  name: pod-07
spec:
  containers:
  - name: receive
    image: pavanidevops78/kubernetes:r1
    volumeMounts:
    - name: data-path
      mountPath: /data/db_host_value
  initContainers:
  - name: send
    image: pavanidevops78/kubernetes:s1
    env:
    - name: "DB_HOST"
      value: "MYSQL"
    volumeMounts:
    - name: data-path
      mountPath: /data/db_host_value
  volumes:
  - name: data-path
    emptyDir: {}

