apiVersion: v1
kind: Pod
metadata:
  name: pod-07
spec:
  containers:
  - name: receive
    image: pavanidevops78/kubernetes:r9
    volumeMounts:
    - name: data-path
      mountPath: /data
  initContainers:
  - name: send
    image: pavanidevops78/kubernetes:s4
    env:
    - name: DB_HOST
      value: "MYSQL"
    volumeMounts:
    - name: data-path
      mountPath: /data
  volumes:
  - name: data-path
    emptyDir: {}

