apiVersion: v1
kind: Pod
metadata:
  name: pod-02
spec:
  initContainers:
  - name: docker-image
    image: pavanidevops78/kubernetes:v2
    env:
     - name: username
       value: "admin"
     - name: password
       value: "admin123"
    volumeMounts:
    - name: mounts-path
      mountPath: /data
  volumes:
  - name: mounts-path
    emptyDir: {}
  containers:
   - name: nginx
     image: nginx
     volumeMounts:
     - name: mounts-path
       mountPath: /data