apiVersion: v1
kind: Pod
metadata:
  name: pod-02
spec:
  initContainers:
  - name: docker-image
    image: nginx
    env:
    - name: username
      image: "admin"
    - name: password
      image: "admin123"
      volumeMounts:
      - name: mounts-path
        mountPath: /data
  volumes:
    - name: mounts-path
      emptyDir: {}
  containers:
   - name: nginx
     image: nginx
     volumeMounts:
     - name: mounts-path
       mountPath: /data