apiVersion: v1
kind: Pod
metadata:
  name: pod-02
spec:
  initContainers:
  - name: docker-image
    image: public.ecr.aws/u4j6q5s8/learn-kubernetes:v1
    env:
     - name: username
       value: "admin"
     - name: password
       value: "admin123"
    volumeMounts:
    - name: mounts-path
      mountPath: /usr/share/nginx/html
  volumes:
  - name: mounts-path
    emptyDir: {}
  containers:
   - name: receive
     image: public.ecr.aws/u4j6q5s8/learn-jenkins:v1
     volumeMounts:
     - name: mounts-path
       mountPath: /usr/share/nginx/html