apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  initContainers:
  - name: vault
    image: public.ecr.aws/u4j6q5s8/vault-init-container:v1
    env:
    - name: VAULT_ADDR
      value: "https://54.227.58.60:8200/"
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
         name: vault-token
         key: token
         optional: true
    - name: SECRET_NAME
      value: common/backend
    - name: VAULT_SKIP_VERIFY
      value: "TRUE"
    volumeMounts:
    - mountPath: /data
      name: vault
  volumes:
  - name: vault
    emptyDir:
      sizeLimit: 5Mi

  containers:
    - name: backend
      image: public.ecr.aws/u4j6q5s8/expense-backend:v1
      volumeMounts:
        - mountPath: /data
          name: vault



