apiVersion: v1
kind: Pod
metadata:
  name: backend-vault
spec:
  initContainers:
    - name: vault
      image: 041445559784.dkr.ecr.us-east-1.amazonaws.com/vault-init-container:v2
      env:
        - name: VAULT_ADDR
          value: https://54.91.44.61:8200/
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/backend
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
  containers:
    - name: nginx
      image: nginx



