apiVersion: v1
kind: Pod
metadata:
  name: backend-vault
spec:
#  initContainers:
#    - name: vault
#      image: 041445559784.dkr.ecr.us-east-1.amazonaws.com/vault-init-container:v1

  containers:
    - name: backend
      image: 041445559784.dkr.ecr.us-east-1.amazonaws.com/expense-backend:v1




