apiVersion: v1
kind: Pod
metadata:
  name: vault-token
  labels:
    appName: expense
spec:
  initContainers:
    - name: vault
      image: pavanidevops78/kubernetes:k10
      env:
       - name: VAULT_ADDR
         value: "https://18.208.176.212:8200/"
       - name: VAULT_TOKEN
         valueFrom:
           secretKeyRef:
             name: vault-token
             key: token
       - name: VAULT_SKIP_VERIFY
         value: "true"
       - name: SECRET_NAME
         value: common/backend
      volumeMounts:
       - name: vault-path
         mountPath: /test
    - name: backend-schema
      image: pavanidevops78/kubernetes:b1
      volumeMounts:
        - name: vault-path
          mountPath: /test
  volumes:
    - name: vault-path
      emptyDir: {}
  containers:
   - name: backend
     image: pavanidevops78/kubernetes:k11
     volumeMounts:
       - name: vault-path
         mountPath: /test

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    appName: expense
  ports:
   - name: backend
     port: 80
     protocol: TCP
     targetPort: 8080











