apiVersion: v1
kind: Pod
metadata:
  name: vault-token
spec:
  initContainers:
    - name: vault
      image: docker-image
      volumeMounts:
        - name: vault-path
          mountPath: /data
      env:
       - name: VAULT_ADDR
         value: "https://54.80.29.0:8200/"
       - name: VAULT_TOKEN
         valueFrom:
           secretsFrom:
             name: vault-token
             key: token
       - name: SECRETS_COMMON
         value: common/backend
  volumes:
    - name: vault-path
      emptyDir: {}
  containers:
   - name: backend
     image: docker-image
     volumeMounts:
       - name: vault-path
         mountPath: /data