apiVersion: v1
kind: Pod
metadata:
  name: vault-token
spec:
  initContainers:
    - name: vault
      image: pavanidevops78/kubernetes:k9
      env:
       - name: VAULT_ADDR
         value: "https://3.90.20.211:8200/"
       - name: VAULT_TOKEN
         valueFrom:
           secretKeyRef:
             name: vault-token
             key: token
       - name: VAULT_SKIP_VERIFY
         value: "true"
       - name: SECRET_NAME
         value: common/backend
      volumeMounts:
       - name: vault-path
         mountPath: /test
  volumes:
    - name: vault-path
      emptyDir: {}
  containers:
   - name: backend
     image: pavanidevops78/kubernetes:k7
     volumeMounts:
       - name: vault-path
         mountPath: /test

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: service-01
#spec:
#  selectors:
#    appName: backend





