apiVersion: v1
kind: Pod
metadata:
  name: vault-token
  labels:
    appName: backend
spec:
  initContainers:
    - name: vault
      image: pavanidevops78/kubernetes:k1
      env:
       - name: VAULT_ADDR
         value: "https://3.90.20.211:8200/"
       - name: VAULT_TOKEN
         valueFrom:
           secretKeyRef:
             name: vault-token
             key: token
       - name: SECRET_NAME
         value: common/backend

      volumeMounts:
       - name: vault-path
         mountPath: /data

  volumes:
    - name: vault-path
      emptyDir: {}
  containers:
   - name: backend
     image: pavanidevops78/kubernetes:b8
     volumeMounts:
       - name: vault-path
         mountPath: /data

---
apiVersion: v1
kind: Service
metadata:
  name: service-01
spec:
  selectors:
    appName: backend
  ports:
    - name: backend
      port: 80
      protocol: TCP
      targetPort: 8080




