apiVersion: v1
kind: Pod
metadata:
  name: vault-token
spec:
  initContainers:
    - name: vault
      image: pavanidevops78/kubernetes:b1
      env:
       - name: VAULT_ADDR
         value: "https://54.80.29.0:8200/"
#       - name: VAULT_TOKEN
#         valueFrom:
#           secretRefKey:
#             name: vault-token
#             key: token
#       - name: SECRET_NAME
#         value: common/backend
#  volumeMounts:
#    - name: vault-path
#      mountPath: /data
#
#  volumes:
#    - name: vault-path
#      emptyDir: {}
  containers:
   - name: backend
     image: pavanidevops78/kubernetes:b2
     volumeMounts:
       - name: vault-path
         mountPath: /data